services:

  messagebroker:
    image: rabbitmq:management

  mongodb:
    image: mongo:6

  mongo-express:
    image: mongo-express


  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
   
  kib01:
    image: docker.elastic.co/kibana/kibana:7.9.0



  streaming.producer.api:
    image: ${DOCKER_REGISTRY-}streamingproducerapi
    build:
      context: .
      dockerfile: Services/Streaming.Producer.API/Dockerfile


  streaming.processor:
    image: ${DOCKER_REGISTRY-}streamingprocessor
    build:
      context: .
      dockerfile: Services/Streaming.Processor/Dockerfile


volumes:
    mongo-data:
    data01:
      driver: local
  
networks:
  elastic:
    driver: bridge